version: "3.8"

services:
  app:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
      - db_vulnerable
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_VULNERABLE_HOST=db_vulnerable
      - DB_VULNERABLE_PORT=3307
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    entrypoint: ["/entrypoint.sh"]
    command: ["python", "app.py"]

  db:
    image: mysql:8.0
    container_name: mysql_secure
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: secure_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  db_vulnerable:
    image: mysql:8.0
    container_name: mysql_vulnerable
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: vulnerable_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3309:3306"
    volumes:
      - db_vulnerable_data:/var/lib/mysql

volumes:
  db_data:
  db_vulnerable_data:
